-- Generated by Oracle SQL Developer Data Modeler 20.4.0.374.0801
--   at:        2021-09-17 11:03:51 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c
--student id: 30391113
--student name: An Ju
-- Capture run of script in file called mm_schema_output.txt
set echo on
SPOOL mm_schema_output.txt


DROP TABLE assessment CASCADE CONSTRAINTS;

DROP TABLE center CASCADE CONSTRAINTS;

DROP TABLE class CASCADE CONSTRAINTS;

DROP TABLE class_staff CASCADE CONSTRAINTS;

DROP TABLE facility CASCADE CONSTRAINTS;

DROP TABLE member CASCADE CONSTRAINTS;

DROP TABLE member_attendance CASCADE CONSTRAINTS;

DROP TABLE payment CASCADE CONSTRAINTS;

DROP TABLE "SESSION" CASCADE CONSTRAINTS;

DROP TABLE staff CASCADE CONSTRAINTS;

DROP TABLE staff_class CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE assessment (
    member_id      NUMBER(7) NOT NULL,
    assess_date    DATE NOT NULL,
    assess_weight  NUMBER(4) NOT NULL,
    assess_blood   VARCHAR2(20) NOT NULL,
    assess_bmi     VARCHAR2(5) NOT NULL,
    assess_vo      VARCHAR2(5) NOT NULL
);

COMMENT ON COLUMN assessment.member_id IS
    'member id';

COMMENT ON COLUMN assessment.assess_date IS
    'the date member take the assessment';

COMMENT ON COLUMN assessment.assess_weight IS
    'member''s weight in kg';

COMMENT ON COLUMN assessment.assess_blood IS
    'the blood pressure of the member';

COMMENT ON COLUMN assessment.assess_bmi IS
    'the bmi record of the member';

COMMENT ON COLUMN assessment.assess_vo IS
    'the VO2Max record of the member';

ALTER TABLE assessment ADD CONSTRAINT assessment_pk PRIMARY KEY ( assess_date,
                                                                  member_id );

CREATE TABLE center (
    center_id      NUMBER(7) NOT NULL,
    center_name    VARCHAR2(50) NOT NULL,
    center_phone   CHAR(10) NOT NULL,
    center_street  VARCHAR2(50) NOT NULL,
    center_town    VARCHAR2(50) NOT NULL,
    center_post    CHAR(5)
);

COMMENT ON COLUMN center.center_id IS
    'unique center id';

COMMENT ON COLUMN center.center_name IS
    'center name';

COMMENT ON COLUMN center.center_street IS
    'street of the center';

COMMENT ON COLUMN center.center_town IS
    'town of the center';

COMMENT ON COLUMN center.center_post IS
    'postcode of the center';

ALTER TABLE center ADD CONSTRAINT center_pk PRIMARY KEY ( center_id );

CREATE TABLE class (
    center_id     NUMBER(7) NOT NULL,
    class_no      NUMBER(7) NOT NULL,
    class_start   DATE NOT NULL,
    class_cost    CHAR(5) NOT NULL,
    class_maxno   NUMBER(3),
    class_sessno  NUMBER(3) NOT NULL,
    class_desc    VARCHAR2(70),
    class_type    VARCHAR2(50) NOT NULL,
    class_gender  CHAR(5) NOT NULL,
    class_mins    NUMBER(4) NOT NULL,
    facility_no   NUMBER(7) NOT NULL,
    center_id2    NUMBER(7) NOT NULL
);

ALTER TABLE class
    ADD CONSTRAINT chk_class_gender CHECK ( class_gender IN ( 'F', 'M', 'N' ) );

COMMENT ON COLUMN class.center_id IS
    'unique center id';

COMMENT ON COLUMN class.class_no IS
    'class number of the class in the center';

COMMENT ON COLUMN class.class_start IS
    'start date and time of the class';

COMMENT ON COLUMN class.class_cost IS
    'the cost of the class';

COMMENT ON COLUMN class.class_maxno IS
    'the maximum number of the people attend this class';

COMMENT ON COLUMN class.class_sessno IS
    'the session number of the class';

COMMENT ON COLUMN class.class_desc IS
    'Class decription';

COMMENT ON COLUMN class.class_type IS
    'the type of the class';

COMMENT ON COLUMN class.class_gender IS
    'whether this class is gender specific ''M'' for male ''F'' for female ''M'' for unrestricted';

COMMENT ON COLUMN class.class_mins IS
    'the duration of the class';

COMMENT ON COLUMN class.facility_no IS
    'facility room number';

COMMENT ON COLUMN class.center_id2 IS
    'unique center id';

ALTER TABLE class ADD CONSTRAINT class_pk PRIMARY KEY ( class_no,
                                                        center_id );

CREATE TABLE class_staff (
    cstaff_leader  VARCHAR2(5) NOT NULL,
    staff_id       NUMBER(7) NOT NULL,
    class_no       NUMBER(7) NOT NULL,
    center_id      NUMBER(7) NOT NULL,
    cstaff_no      NUMBER(7) NOT NULL
);

COMMENT ON COLUMN class_staff.cstaff_leader IS
    'whether the staff is the leader of the class';

COMMENT ON COLUMN class_staff.staff_id IS
    'the id number of the staff';

COMMENT ON COLUMN class_staff.class_no IS
    'class number of the class in the center';

COMMENT ON COLUMN class_staff.center_id IS
    'unique center id';

COMMENT ON COLUMN class_staff.cstaff_no IS
    'the arrangement of the staff in the class (surrogate key)';

ALTER TABLE class_staff ADD CONSTRAINT class_staff_pk PRIMARY KEY ( cstaff_no );

ALTER TABLE class_staff
    ADD CONSTRAINT class_staff_nk UNIQUE ( cstaff_leader,
                                           staff_id,
                                           class_no,
                                           center_id );

CREATE TABLE facility (
    center_id      NUMBER(7) NOT NULL,
    facility_no    NUMBER(7) NOT NULL,
    facility_name  VARCHAR2(20) NOT NULL,
    facility_desc  VARCHAR2(50),
    facility_capa  NUMBER(3) NOT NULL
);

COMMENT ON COLUMN facility.center_id IS
    'unique center id';

COMMENT ON COLUMN facility.facility_no IS
    'facility room number';

COMMENT ON COLUMN facility.facility_name IS
    'facility name';

COMMENT ON COLUMN facility.facility_desc IS
    'the description of the facility';

COMMENT ON COLUMN facility.facility_capa IS
    'the number of participants it can accommodate';

ALTER TABLE facility ADD CONSTRAINT facility_pk PRIMARY KEY ( facility_no,
                                                              center_id );

CREATE TABLE member (
    member_id     NUMBER(7) NOT NULL,
    member_fname  VARCHAR2(20) NOT NULL,
    member_lname  VARCHAR2(20) NOT NULL,
    member_addr   VARCHAR2(50) NOT NULL,
    member_phone  CHAR(10) NOT NULL,
    member_date   DATE NOT NULL,
    member_id2    NUMBER(7),
    center_id     NUMBER(7) NOT NULL
);

COMMENT ON COLUMN member.member_id IS
    'member id';

COMMENT ON COLUMN member.member_fname IS
    'member''s first name';

COMMENT ON COLUMN member.member_lname IS
    'member''s last name';

COMMENT ON COLUMN member.member_addr IS
    'member''s address';

COMMENT ON COLUMN member.member_phone IS
    'member''s phone number';

COMMENT ON COLUMN member.member_date IS
    'the date which the mumber joined the movement';

COMMENT ON COLUMN member.member_id2 IS
    'member id';

COMMENT ON COLUMN member.center_id IS
    'unique center id';

ALTER TABLE member ADD CONSTRAINT member_pk PRIMARY KEY ( member_id );

CREATE TABLE member_attendance (
    payment_date     DATE NOT NULL,
    memberatd_total  NUMBER(3) NOT NULL,
    member_id        NUMBER(7) NOT NULL,
    class_no         NUMBER(7) NOT NULL,
    center_id        NUMBER(7) NOT NULL,
    memberatd_no     NUMBER(7) NOT NULL
);

COMMENT ON COLUMN member_attendance.payment_date IS
    'the date the member make the payment';

COMMENT ON COLUMN member_attendance.memberatd_total IS
    'the member''s total attendance of the class';

COMMENT ON COLUMN member_attendance.member_id IS
    'member id';

COMMENT ON COLUMN member_attendance.class_no IS
    'class number of the class in the center';

COMMENT ON COLUMN member_attendance.center_id IS
    'unique center id';

COMMENT ON COLUMN member_attendance.memberatd_no IS
    'attendance report number (surrogate key)';

ALTER TABLE member_attendance ADD CONSTRAINT member_attendance_pk PRIMARY KEY ( memberatd_no );

ALTER TABLE member_attendance
    ADD CONSTRAINT member_attendance_nk UNIQUE ( payment_date,
                                                 memberatd_total,
                                                 member_id,
                                                 class_no,
                                                 center_id );

CREATE TABLE payment (
    member_id     NUMBER(7) NOT NULL,
    payment_date  DATE NOT NULL,
    payment_no    NUMBER(4) NOT NULL
);

COMMENT ON COLUMN payment.member_id IS
    'member id';

COMMENT ON COLUMN payment.payment_date IS
    'the date member make the payment';

COMMENT ON COLUMN payment.payment_no IS
    'payment number (surrogate key)';

ALTER TABLE payment ADD CONSTRAINT payment_pk PRIMARY KEY ( payment_no );

ALTER TABLE payment ADD CONSTRAINT payment_nk UNIQUE ( member_id,
                                                       payment_date );

CREATE TABLE "SESSION" (
    sess_date     VARCHAR2(5) NOT NULL,
    memberatd_no  NUMBER(7) NOT NULL
);

COMMENT ON COLUMN "SESSION".sess_date IS
    'whether the member attend the class';

COMMENT ON COLUMN "SESSION".memberatd_no IS
    'attendance report number (surrogate key)';

ALTER TABLE "SESSION" ADD CONSTRAINT session_pk PRIMARY KEY ( memberatd_no );

CREATE TABLE staff (
    staff_id     NUMBER(7) NOT NULL,
    staff_fname  VARCHAR2(20) NOT NULL,
    staff_lname  VARCHAR2(20) NOT NULL,
    staff_phone  NUMBER(10) NOT NULL,
    staff_date   DATE NOT NULL,
    staff_role   CHAR 
/*  WARNING: CHAR size not specified */
     NOT NULL,
    staff_faid   VARCHAR2(5) NOT NULL,
    center_id    NUMBER(7) NOT NULL
);

ALTER TABLE staff
    ADD CONSTRAINT chk_staff_role CHECK ( staff_role IN ( 'A', 'C', 'D', 'M', 'P',
                                                          'S', 'T' ) );

COMMENT ON COLUMN staff.staff_id IS
    'the id number of the staff';

COMMENT ON COLUMN staff.staff_fname IS
    'staff''s first name';

COMMENT ON COLUMN staff.staff_lname IS
    'staff''s last name';

COMMENT ON COLUMN staff.staff_phone IS
    'phone number of the staff';

COMMENT ON COLUMN staff.staff_date IS
    'the date the staff started at the center';

COMMENT ON COLUMN staff.staff_role IS
    'Administration (A) Cleaner (C) Instructor Dry (D) Instructor Pool (P) Manager (only one per centre) (M) Sales (S) Security (T)';

COMMENT ON COLUMN staff.staff_faid IS
    'whether the staff is first aid certified';

COMMENT ON COLUMN staff.center_id IS
    'unique center id';

ALTER TABLE staff ADD CONSTRAINT staff_pk PRIMARY KEY ( staff_id );

CREATE TABLE staff_class (
    staff_id   NUMBER(7) NOT NULL,
    class_no   NUMBER(7) NOT NULL,
    center_id  NUMBER(7) NOT NULL
);

ALTER TABLE staff_class
    ADD CONSTRAINT staff_class_pk PRIMARY KEY ( staff_id,
                                                class_no,
                                                center_id );

ALTER TABLE class
    ADD CONSTRAINT center_class FOREIGN KEY ( center_id )
        REFERENCES center ( center_id );

ALTER TABLE facility
    ADD CONSTRAINT center_facility FOREIGN KEY ( center_id )
        REFERENCES center ( center_id );

ALTER TABLE class_staff
    ADD CONSTRAINT class_staff_class FOREIGN KEY ( class_no,
                                                   center_id )
        REFERENCES class ( class_no,
                           center_id );

ALTER TABLE class
    ADD CONSTRAINT facility FOREIGN KEY ( facility_no,
                                          center_id2 )
        REFERENCES facility ( facility_no,
                              center_id );

ALTER TABLE assessment
    ADD CONSTRAINT member_assessment FOREIGN KEY ( member_id )
        REFERENCES member ( member_id );

ALTER TABLE member_attendance
    ADD CONSTRAINT member_attendance_class FOREIGN KEY ( class_no,
                                                         center_id )
        REFERENCES class ( class_no,
                           center_id );

ALTER TABLE member_attendance
    ADD CONSTRAINT member_attendance_member FOREIGN KEY ( member_id )
        REFERENCES member ( member_id );

ALTER TABLE "SESSION"
    ADD CONSTRAINT member_attendance_seesion FOREIGN KEY ( memberatd_no )
        REFERENCES member_attendance ( memberatd_no );

ALTER TABLE member
    ADD CONSTRAINT member_center FOREIGN KEY ( center_id )
        REFERENCES center ( center_id );

ALTER TABLE member
    ADD CONSTRAINT member_member FOREIGN KEY ( member_id2 )
        REFERENCES member ( member_id );

ALTER TABLE payment
    ADD CONSTRAINT member_payment FOREIGN KEY ( member_id )
        REFERENCES member ( member_id );

ALTER TABLE staff
    ADD CONSTRAINT staff_center FOREIGN KEY ( center_id )
        REFERENCES center ( center_id );

ALTER TABLE staff_class
    ADD CONSTRAINT staff_class_class_fk FOREIGN KEY ( class_no,
                                                      center_id )
        REFERENCES class ( class_no,
                           center_id );

ALTER TABLE class_staff
    ADD CONSTRAINT staff_class_staff FOREIGN KEY ( staff_id )
        REFERENCES staff ( staff_id );

ALTER TABLE staff_class
    ADD CONSTRAINT staff_class_staff_fk FOREIGN KEY ( staff_id )
        REFERENCES staff ( staff_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             31
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 1
SPOOL off
set echo off